dist: trusty
addons:
  chrome: stable
language: node_js
cache:
  directories:
  - node_modules
env:
  global:
  - SAUCE_REGION: 'eu'
  - secure: MXZSiwkITO3LSngHmAyue+djuzyklfMApKNeKrWDR4Jy6MrNhYLocpd5qoV51MwIxQrnGcIjMof4sRzQ74+WwgH8Wt9zT02BOg4L0p0XEXpHbBwmXpu/2YGkd26SAZK4uiy1gYmcyIfFrQbYKNiZjGjFA/F0VpYkmruCxV6+3UeR2hyrdFwvE11t5ZtkBnBtvSm8Tg4uL/M/tCc22nUxFHQJ9HILW4wI25RfVYLZNzy4cD7AgfCD5nfoIqs3Wzv16qQ6wnX/FsrVCgbGRgCnsew76c1Z5/gXQEGYP6O/ZaIpuWoCmunLS6j2luaMKLNkA03TS775juh72BjNP2oifXrlLD3PuoyW0BoJbXgnbNnJm5l6WomydYzPVgFonThtvXz5AWeZVMcVSdAk2dTA28tzSxn55h4mOsigErWaM9z3deNC+VFTm/cWsJEaD5I88X5ZCeNoun8jvUVNgZ3eMBGIPKYNWqv98boZwgPRQ6JZB+86A33BQgVQMMSX7MXbWwMU4H0jYRh9oFq+TA+dUHWQFs2pLktAIGTzzGpNRucDknEo34/bIUXIPm4tqhdEC7jBOzYxhnA1qqz9PMdzE+2PFLYrw8vae3Y9M0hAJEFZcntnakuwUJpeTrrAJAItJfDGdB54PF6JqIa7+c5yHsMt3xkQyAJJVNb+/m5ISIw=
  - secure: 428EnA+ndktp85/6pum1GHHEUwdYdvbJZQsiTkUtPaBlTfVvRGY855dBrYN3C2854+0ZQvldhwDxro4I8TPKShpRxYreDkjtCWXBAbNGvpx1t2ZQPv7+mBI2pGxHtTltTCRPMt/m3KSYPPxgdtZuC9v9pDD3rEfgcwikUgroEzG3f9+tBLbKLHLgCHxwC7JlK4isu5fEklqV36j8O0sgfEBtBmvjuLLxeJEPJNV56VPQ6fXJ+be89DIjvQ5bCgzZN2NL80bXZHcrBykiFtnePCwEbHc0c+yRWZEwXk7i0YbF1sfVyFSaGX+kYlFJvbMe8672yro32JOJYRf+TVoVmO0kn+kVxSy+PIRMtMAvMui0ZGvRN3mmjbGELX647miIg740K920TZqe9EhtYXDWRCBWXn9qG3mF3yqW3nJqN+D13yjyuEdbHmW9cUZvS5YeUCW5wNTmmnw2Dh21y/77TauSB42qveG8w+hduMImlOdiS9eObnWk5yyAUwS1dU2xqF8hsGj04350M4GVtHlUybJ+bmv68MTMGc/2NevYeDzChl0dEn39D4u56TVzEbPBLt0oDLUDXWSQVtRG4zaUgat6zjzaFKXyLDZHA//9nUbd3u199v3Q2lxCzx8hc550dpgGpM3cMK72biIbC/CBJXt7s6MA9p13OX8X6l/ZO1o=
